apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: "consumer-namespace"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-application
  template:
    metadata:
      labels:
        app: consumer-application
    spec:
      containers:
      - name: consumer
        image: ayatachibana/testh2:0.0.62
        volumeMounts:
        - mountPath: /mnt/h2
          name: persistentvolume
        ports:
          - containerPort: 8081
        #readinessProbe:
        #  httpGet:
        #    path: /check
        #    port: 8081
        #  initialDelaySeconds: 15
        #  periodSeconds: 3
        #  timeoutSeconds: 5
        #livenessProbe:
        #  tcpSocket:
        #    port: 8081
        #  initialDelaySeconds: 15
      volumes:
      - name: persistentvolume
        persistentVolumeClaim:
          claimName: consumer-persistentvolumeclaim
  strategy:
    type: RollingUpdate