apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-networkpolicy-ingress
  namespace: "testh2-namespace"
  labels:
    app: testh2
    app.kubernetes.io/name: testh2app
spec:
  podSelector:
    matchLabels:
      app: testh2
      app.kubernetes.io/name: testh2app
  policyTypes:
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: "test-namespace"
      podSelector:
        matchLabels:
          app: test
          app.kubernetes.io/name: testapp
    ports:
      - protocol: TCP
        port: 8081