apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testh2-persistentvolumeclaim
  namespace: "testh2-namespace"
  labels:
    app: test
    app.kubernetes.io/name: testapp
spec:
  storageClassName: ""
  volumeName: testh2-persistentvolume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G