apiVersion: v1
kind: PersistentVolume
metadata:
  name: consumer-persistentvolume
  namespace: "consumer-namespace"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1G
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: "/pv/h2"