apiVersion: v1
kind: Service
metadata:
  name: testh2-service
  namespace: "testh2-namespace"
  labels:
    app: testh2
spec:
  type: ClusterIP
  selector:
    app: testh2
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8081